SimpleCurd.Web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SimpleCurd.DataAccess.Interface;
using SimpleCurd.Model;
using SimpleCurd.Web.Helper;
using SimpleCurd.Web.Models;
using System.Drawing.Printing;

namespace SimpleCurd.Web.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRoleServices _rolesServices;
        public RoleController(IRoleServices rolesServices)
        {
            _rolesServices = rolesServices;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            RoleDto newrole = new RoleDto();
            if (id == 0)
            {
                return View(newrole);
            }

            var role = await _rolesServices.GetRoleAsync(id);

            if (role == null)
            {
                return RedirectToAction("Index");
            }
            return View(role.ToModel());
        }
        [HttpPost]
        public async Task<IActionResult> GetAllRoles([FromBody] Table request)
        {
            var roles = await _rolesServices.GetAllRoleAsync(request);
            return Json(new 
            {
                draw = request.draw,
                recordsTotal = roles.totalRecords,
                recordsFiltered = roles.filteredrecords,
                data = roles.data.ToModelList()
            });
        }
        [HttpGet]
        public async Task<IActionResult> AddOrUpdate(int? id)
        {
            if (id == null || id == 0)
            {
                return View(new RoleDto());
            }

            var role = await _rolesServices.GetRoleAsync(id.Value);
            if (role == null)
            {
                return View(new RoleDto());
            }

            return View(role.ToModel());
        }
        [HttpPost]
        public async Task<IActionResult> Inset(RoleDto model)
        {
            if (!ModelState.IsValid)
                return Json(new { success = false, message = "Invalid form data." });

            var entity = model.ToEntity();
            if (model.Id == 0)
            {
                var existingRole = await _rolesServices.IsExistByNameAsync(model.Name);
                if (existingRole)
                {
                    return Json(new { success = false, message = "Role name already exists." });
                }

                await _rolesServices.CreateRoleAsync(entity);
                return Json(new { success = true, message = "Role added successfully." });
            }
            else
            {
                var existingRole = await _rolesServices.GetRoleAsync(model.Id);

                if (existingRole == null)
                    return Json(new { success = false, message = "Role not found." });


                existingRole.Name = model.Name;
                existingRole.Description = model.Description;

                await _rolesServices.UpdateRoleAsync(existingRole);
                return Json(new { success = true, message = "Role updated successfully." });
            }
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return Json(new { success = true, message = "Role Not Found." });
            }
            var isDeleted = await _rolesServices.DeleteRoleAsync(id);

            if (isDeleted)
            {
                return Json(new { success = true, message = "Role Deleted successfully." });
            }

            return Json(new { success = false, message = "Role Not Deleted." });
        }
        public async Task<IActionResult> ReActiveRole(int id)
        {
            if (id == 0)
            {
                return Json(new { success = false, message = "Role Not Found." });
            }
            var role = await _rolesServices.GetRoleAsync(id);
            if (role == null)
            {
                return Json(new { success = false, message = "Role Not Found." });
            }
            role.IsActive = true;
            await _rolesServices.UpdateRoleAsync(role);
            return Json(new { success = true, message = "Role Actived successfully." });
        }
    }
}

SimpleCurd.Web/Views/Role/AddOrUpdate.cshtml
@model RoleDto

<div class="row">
    <div class="col-lg-12 col-md-12 col-12">
        <div class="mb-8 d-md-flex justify-content-between align-items-center">
            <div>
                <h1 class="mb-3 h2">
                    @if (Model.IsActive == false && Model.Id > 0)
                    {
                        @("Role Deactive")
                    }
                    else
                    {
                        @(Model.Id > 0 ? "Update Role" : "Create Role")
                    }
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Role">Role</a></li>
                        <li class="breadcrumb-item active" aria-current="page">
                            @if (Model.IsActive == false && Model.Id > 0)
                            {
                                @("Role Deactive")
                            }
                            else
                            {
                                @(Model.Id > 0 ? "Update Role" : "Create Role")
                            }
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div>
    <!-- row -->
    <div class="row mb-6">
        <div class="col-xxl-9 col-xl-8 col-md-12 col-12">
            <form id="rolefrm">
                <input asp-for="Id" hidden/>
                <div class="card card-lg mb-6">
                    <div class="card-body px-6 py-5">
                        <div class="row g-3">
                            <div class="col-12">
                                <label class="form-label" asp-for="Name">
                                    Name
                                    <span class="text-danger">*</span>
                                </label>
                                @if (Model.IsActive == false && Model.Id > 0)
                                {
                                    <input type="text" class="form-control" asp-for="Name" placeholder="Enter project title" disabled>
                                }
                                else
                                {
                                    <input type="text" class="form-control" asp-for="Name" placeholder="Enter project title">
                                }
                            </div>
                            <div class="col-md-6 col-12">
                                <label class="form-label" asp-for="Description">Description</label>
                                @if (Model.IsActive == false && Model.Id > 0)
                                {
                                    <textarea type="text" class="form-control" asp-for="Description" placeholder="Description" disabled></textarea>
                                }
                                else
                                {
                                    <textarea type="text" class="form-control" asp-for="Description" placeholder="Description"></textarea>
                                }
                            </div>

                            <div class="col-md-3 col-12">
                            </div>

                        </div>
                    </div>
                </div>
            </form>
            <div class="card card-lg mb-6">
            </div>
            <div class="mt-4 d-flex justify-content-end">
                <a asp-action="Index" asp-controller="Role" class="btn btn-dark m-1">Back Role</a>
                @if (Model.IsActive == false && Model.Id > 0)
                {
                    <button class="btn btn-subtle-primary me-2 m-1" id="reactiveBtn" data-id="@Model.Id">Reactive</button>
                }
                else
                {
                    @if (Model.Id > 0)
                    {
                        <button class="btn btn-primary me-2 m-1" id="updateBtn">Update</button>
                    }
                    else
                    {
                        <button class="btn btn-primary me-2 m-1" id="createBtn">Create</button>
                    }
                }
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
         $(document).ready(function() {
            $("#createBtn, #updateBtn").click(function() {
                let detail = $("#rolefrm").serialize();

                if (!$("#rolefrm").valid()) {
                    return;
                }

                $.ajax({
                      url: '@Url.Action("Inset", "Role")',
                      method: 'Post',
                      data: detail, 
                      dataType: 'json',
                      success: function(response) {
                        if(response.success){
                            $("#Name").val('');
                            $("#Description").val('');

                            Swal.fire({ title: "Drag me!",icon: "success", draggable: true });
                        }else{
                            Swal.fire({icon: "error", title: "Oops...", text: response.message,});
                        }
                      },
                      error: function(xhr, status, error) {
                        console.error('Error:', error);
                        Swal.fire({icon: "error", title: "Oops...", text: "Something went wrong!",});
                      },
                });
            });

            $("#reactiveBtn").on("click", function () {
            let id = $(this).data("id");
               $.ajax({
                url: '@Url.Action("ReActiveRole", "Role")' + '/' + id,
                success: function(result) {
                    if(result.success == true){
                        location.reload();
                    }
                },
               });
            });
        });
    </script>
}

SimpleCurd.Web/Views/Role/Index.cshtml
<div class="row">
    <div class="col-lg-12 col-md-12 col-12">
        <!-- Page header -->
        <div class="mb-8 d-md-flex justify-content-between align-items-center">
            <div>
                <h1 class="mb-3 h2">Project Grid</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="AddOrUpdate" asp-controller="Home">Home</a></li>
                        <li class="breadcrumb-item"><a asp-action="AddOrUpdate" asp-controller="Role">Role</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Grid</li>
                    </ol>
                </nav>
            </div>
            <div>
                <a asp-action="AddOrUpdate" asp-controller="Role" class="btn btn-dark d-md-flex align-items-center gap-2"> Create new Role</a>
            </div>
        </div>
    </div>
</div>
<div class="row g-6 mb-6">
    <div class="">
        <!-- card -->
        <div class="card card-lg">
            <!-- card header -->
            <div class="card-header border-bottom-0">
                <div class="row g-4">
                    <div class="col-lg-4">
                        <input type="search" class="form-control" placeholder="Search" id="searchInput">
                    </div>
                    <div class="col-lg-8 d-flex justify-content-end">
                        <div class="d-flex align-items-center gap-2">
                            <div>
                                <button type="button" class="btn btn-primary" id="searchBtn">Search</button>
                            </div>
                            <div class="dropdown" id="isActiveDropdown">
                                <a class="btn btn-white dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Category</a>

                                <ul class="dropdown-menu">
                                    <li><span class="dropdown-item" data-active="true">Active</span></li>
                                    <li><span class="dropdown-item" data-active="false">Deactive</span></li>
                                </ul>
                            </div>
                            <div>
                                <button type="button" class="btn btn-white" id="referenceBtn">Reference</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- table -->
            <div class="table-responsive">
                <table class="table text-nowrap mb-0 table-centered table-hover" id="roleTbl">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>CreatedAt</th>
                            <th>IsActive</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>

</div>

@section Scripts {
 <script>
        var table;
        var activeFilter = null;

        $(document).ready(function () {

            table = $('#roleTbl').DataTable({
                processing: true,
                serverSide: true,
                filter: false,
                ajax: {
                    url: '@Url.Action("GetAllRoles", "Role")',
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    data: function (d) {
                         d.Search = { value: $("#searchInput").val(), regex: false };
                         d.IsActive = activeFilter;
                        return JSON.stringify(d);
                    }
                },
                columns: [
                    { data: 'id', name: 'Id' },
                    { data: 'name', name: 'Name' },
                    { data: 'description', name: 'Description' },
                    { data: 'createdAt', name: 'CreatedAt' },
                    {
                        data: 'isActive',
                        name: 'IsActive',
                        orderable: false,
                        render: function (data) {
                            return data
                                ? `<span class="badge text-success-emphasis bg-success-subtle rounded-pill">Active</span>`
                                : `<span class="badge text-danger-emphasis bg-danger-subtle rounded-pill">Deactive</span>`;
                        }
                    },
                    {
                        data: null,
                        orderable: false,
                        render: function (data, type, row) {

                            const updateUrl = '@Url.Action("AddOrUpdate", "Role")' + '/' + row.id;

                            let updateBtn = `
                                <a href="${updateUrl}" class="btn btn-ghost btn-icon btn-sm rounded-circle texttooltip">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" stroke-width="1.5" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                        <path d="M0 0h24v24H0z" stroke="none"></path>
                                        <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1"></path>
                                        <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z"></path>
                                        <path d="M16 5l3 3"></path>
                                    </svg>
                                </a>
                            `;

                            let viewBtn = "";
                            let deleteBtn = "";

                            if (row.isActive) {
                                viewBtn = `
                                    <button class="btn-view-model btn btn-ghost btn-icon btn-sm rounded-circle texttooltip" data-id="${row.id}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" stroke-width="1.5" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                            <path d="M0 0h24v24H0z" stroke="none"></path>
                                            <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                                            <path d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6"></path>
                                        </svg>
                                    </button>
                                `;

                                deleteBtn = `
                                    <button class="btn-delete btn btn-ghost btn-icon btn-sm rounded-circle texttooltip" data-id="${row.id}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" stroke-width="1.5" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                            <path d="M0 0h24v24H0z" stroke="none"></path>
                                            <path d="M4 7l16 0"></path>
                                            <path d="M10 11l0 6"></path>
                                            <path d="M14 11l0 6"></path>
                                            <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path>
                                            <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path>
                                        </svg>
                                    </button>
                                `;
                            }

                            return viewBtn + updateBtn + deleteBtn;
                        }
                    }
                ]
            });


            $("#searchBtn").on("click", function() {
                table.draw();
            });

             $("#referenceBtn").on("click", function() {
                 $("#searchInput").val("");
                 activeFilter = null;
                table.ajax.reload();
            });
        });

        // View Modal
        $(document).on("click", ".btn-view-model", function () {
            let id = $(this).data("id");
            $.get('@Url.Action("View", "Role")' + '/' + id, function (result) {
                $("#mainContent").html(result);
                $('#commonModals').modal('show');
            });
        });

        $(document).on("click", "#isActiveDropdown .dropdown-item", function () {
            activeFilter = $(this).data("active"); // true / false
            table.draw(); // Refresh table data
        });

        // Delete Role
        $(document).on("click", ".btn-delete", function () {
            let id = $(this).data("id");
            $.post('@Url.Action("Delete", "Role")' + '/' + id, function (result) {
                if (result) {
                    table.ajax.reload();
                }
            });
        });

 </script>
}

SimpleCurd.Web/Views/Role/View.cshtml
@model RoleDto
@{
    ViewData["Title"] = "Role";
    Layout = null;
}

<div class="card card-lg mb-6">
    <!-- card body -->
    <div class="card-body">
        <div class="mb-4">
            <h5 class="mb-1">@ViewData["Title"]</h5>
            <span class="text-secondary">Budget Allocation Overview:</span>
        </div>
        <div class="fs-2 fw-bold mb-3">@Model.Name</div>
        <div class="d-flex justify-content-between align-items-center gap-1 w-100 mb-2">
            <div>Description :</div>
            <div>@Model.Description</div>
        </div>
        <div class="d-flex justify-content-between align-items-center gap-1 w-100 mb-4">
            <div>CreatedAt :</div>
            <div>@Model.CreatedAt</div>
        </div>
        <div class="d-flex justify-content-between gap-3">
            @if(Model.IsActive == false){
                <button class="btn btn-danger w-100" disabled>Disactive</button>
            }
            else
            {
                <button class="btn btn-primary w-100" disabled>Active</button>
            }
            <a href="#!" class="btn btn-white w-100">View Details</a>
        </div>
    </div>
</div>