SimpleCurd.Web/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleCurd.DataAccess.Interface;
using SimpleCurd.DataAccess.Services;
using SimpleCurd.Model;
using SimpleCurd.Web.Helper;
using SimpleCurd.Web.Models;

namespace SimpleCurd.Web.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentServices _departmentServices;
        public DepartmentController(IDepartmentServices departmentServices)
        {
            _departmentServices = departmentServices;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            DepartmentDto newDepartmentDto = new DepartmentDto();
            if (id == 0)
            {
                return View(newDepartmentDto);
            }

            var department = await _departmentServices.GetDepartmentAsync(id);

            if (department == null)
            {
                return RedirectToAction("Index");
            }
            return View(department.ToModel());
        }
        [HttpPost]
        public async Task<IActionResult> GetAll([FromBody] Table request)
        {
            var department = await _departmentServices.GetAllDepartmentAsync(request);
            return Json(new
            {
                draw = request.draw,
                recordsTotal = department.totalRecords,
                recordsFiltered = department.filteredrecords,
                data = department.data.ToModelList()
            });
        }
        [HttpGet]
        public async Task<IActionResult> AddOrUpdate(int? id)
        {
            if (id == null || id == 0)
            {
                return View(new DepartmentDto());
            }

            var department = await _departmentServices.GetDepartmentAsync(id.Value);
            if (department == null)
            {
                return View(new DepartmentDto());
            }

            return View(department.ToModel());
        }
        [HttpPost]
        public async Task<IActionResult> Inset(DepartmentDto model)
        {
            if (!ModelState.IsValid)
                return Json(new { success = false, message = "Invalid form data." });

            var entity = model.ToEntity();
            if (model.Id == 0)
            {
                var existingDepartment = await _departmentServices.IsExistByNameAsync(model.Name);
                if (existingDepartment)
                {
                    return Json(new { success = false, message = "Department already exists." });
                }

                await _departmentServices.CreateDepartmentAsync(entity);
                return Json(new { success = true, message = "Department added successfully." });
            }
            else
            {
                var existingDepartment = await _departmentServices.GetDepartmentAsync(model.Id);

                if (existingDepartment == null)
                    return Json(new { success = false, message = "Department not found." });


                existingDepartment.Name = model.Name;
                existingDepartment.Description = model.Description;

                await _departmentServices.UpdateDepartmentAsync(existingDepartment);
                return Json(new { success = true, message = "Department updated successfully." });
            }
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return Json(new { success = true, message = "Department Not Found." });
            }
            var isDeleted = await _departmentServices.DeleteDepartmentAsync(id);

            if (isDeleted)
            {
                return Json(new { success = true, message = "Department Deleted successfully." });
            }

            return Json(new { success = false, message = "Department Not Deleted." });
        }
        public async Task<IActionResult> ReActiveRole(int id)
        {
            if (id == 0)
            {
                return Json(new { success = false, message = "Department Not Found." });
            }
            var role = await _departmentServices.GetDepartmentAsync(id);
            if (role == null)
            {
                return Json(new { success = false, message = "Department Not Found." });
            }
            role.IsActive = true;
            await _departmentServices.UpdateDepartmentAsync(role);
            return Json(new { success = true, message = "Department Actived successfully." });
        }
    }
}

SimpleCurd.Web/Views/Department/AddOrUpdate.cshtml
@model DepartmentDto

<div class="row">
    <div class="col-lg-12 col-md-12 col-12">
        <div class="mb-8 d-md-flex justify-content-between align-items-center">
            <div>
                <h1 class="mb-3 h2">
                    @if (Model.IsActive == false && Model.Id > 0)
                    {
                        @("Deactive")
                    }
                    else
                    {
                        @(Model.Id > 0 ? "Update" : "Create")
                    }
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Department">Department</a></li>
                        <li class="breadcrumb-item active" aria-current="page">
                            @if (Model.IsActive == false && Model.Id > 0)
                            {
                                @("Deactive")
                            }
                            else
                            {
                                @(Model.Id > 0 ? "Update" : "Create")
                            }
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div>
    <!-- row -->
    <div class="row mb-6">
        <div class="col-xxl-9 col-xl-8 col-md-12 col-12">
            <form id="departmentfrm">
                <input asp-for="Id" hidden />
                <div class="card card-lg mb-6">
                    <div class="card-body px-6 py-5">
                        <div class="row g-3">
                            <div class="col-12">
                                <label class="form-label" asp-for="Name">
                                    Name
                                    <span class="text-danger">*</span>
                                </label>
                                @if (Model.IsActive == false && Model.Id > 0)
                                {
                                    <input type="text" class="form-control" asp-for="Name" placeholder="Enter project title" disabled>
                                }
                                else
                                {
                                    <input type="text" class="form-control" asp-for="Name" placeholder="Enter project title">
                                }
                            </div>
                            <div class="col-md-6 col-12">
                                <label class="form-label" asp-for="Description">Description</label>
                                @if (Model.IsActive == false && Model.Id > 0)
                                {
                                    <textarea type="text" class="form-control" asp-for="Description" placeholder="Description" disabled></textarea>
                                }
                                else
                                {
                                    <textarea type="text" class="form-control" asp-for="Description" placeholder="Description"></textarea>
                                }
                            </div>

                            <div class="col-md-3 col-12">
                            </div>

                        </div>
                    </div>
                </div>
            </form>
            <div class="card card-lg mb-6">
            </div>
            <div class="mt-4 d-flex justify-content-end">
                <a asp-action="Index" asp-controller="Department" class="btn btn-dark m-1">Back</a>
                @if (Model.IsActive == false && Model.Id > 0)
                {
                    <button class="btn btn-subtle-primary me-2 m-1" id="reactiveBtn" data-id="@Model.Id">Reactive</button>
                }
                else
                {
                    @if (Model.Id > 0)
                    {
                        <button class="btn btn-primary me-2 m-1" id="updateBtn">Update</button>
                    }
                    else
                    {
                        <button class="btn btn-primary me-2 m-1" id="createBtn">Create</button>
                    }
                }
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
         $(document).ready(function() {
            $("#createBtn, #updateBtn").click(function() {
                let detail = $("#departmentfrm").serialize();

                if (!$("#departmentfrm").valid()) {
                    return;
                }

                $.ajax({
                      url: '@Url.Action("Inset", "Department")',
                      method: 'Post',
                      data: detail,
                      dataType: 'json',
                      success: function(response) {
                        if(response.success){
                            $("#Name").val('');
                            $("#Description").val('');

                            Swal.fire({ title: "Drag me!",icon: "success", draggable: true });
                        }else{
                            Swal.fire({icon: "error", title: "Oops...", text: response.message,});
                        }
                      },
                      error: function(xhr, status, error) {
                        console.error('Error:', error);
                        Swal.fire({icon: "error", title: "Oops...", text: "Something went wrong!",});
                      },
                });
            });

            $("#reactiveBtn").on("click", function () {
            let id = $(this).data("id");
               $.ajax({
                url: '@Url.Action("ReActiveRole", "Department")' + '/' + id,
                success: function(result) {
                    if(result.success == true){
                        location.reload();
                    }
                },
               });
            });
        });
    </script>
}

SimpleCurd.Web/Views/Department/View.cshtml
@model DepartmentDto
@{
    ViewData["Title"] = "Department";
    Layout = null;
}

<div class="card card-lg mb-6">
    <!-- card body -->
    <div class="card-body">
        <div class="mb-4">
            <h5 class="mb-1">@ViewData["Title"]</h5>
            <span class="text-secondary">Budget Allocation Overview:</span>
        </div>
        <div class="fs-2 fw-bold mb-3">@Model.Name</div>
        <div class="d-flex justify-content-between align-items-center gap-1 w-100 mb-2">
            <div>Description :</div>
            <div>@Model.Description</div>
        </div>
        <div class="d-flex justify-content-between align-items-center gap-1 w-100 mb-4">
            <div>CreatedAt :</div>
            <div>@Model.CreatedAt</div>
        </div>
        <div class="d-flex justify-content-between gap-3">
            @if (Model.IsActive == false)
            {
                <button class="btn btn-danger w-100" disabled>Disactive</button>
            }
            else
            {
                <button class="btn btn-primary w-100" disabled>Active</button>
            }
            <a href="#!" class="btn btn-white w-100">View Details</a>
        </div>
    </div>
</div>